# Generated by Django 3.0.4 on 2020-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], default='non defini', max_length=20)),
                ('form_platform', models.CharField(choices=[('tablet', 'tablet'), ('phone', 'phone')], default='non defini', max_length=20)),
                ('model', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
